# Testar Modeller

## Imports

In [34]:
import sys
from pathlib import Path

import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    HistGradientBoostingRegressor
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from src.validate_process import validate_data

## Utvärderingsfunktion

In [35]:
def evaluate_model(model_name, y_true, y_pred):

    mae = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2 = r2_score(y_true, y_pred)

    print(f"\n=== {model_name} ===")
    print(f"MAE:  {mae:.3f}")
    print(f"RMSE: {rmse:.3f}")
    print(f"R²:   {r2:.3f}")

    return {
        "Model": model_name,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
    }

## Läs Data

In [36]:
df = pd.read_csv(
    "../data/validated/train_validated_2023-05-26_2025-12-31.csv"
)

print(df.shape)

(22825, 7)

## Preprocessing

In [37]:
df = validate_data(df)

print(df.shape)
print(df.head())
print(df.dtypes)
print(df.isna().sum())

(22825, 7)
                        tid    pm25  Lufttemperatur  Vindriktning  \
0 2023-05-26 00:00:00+02:00     NaN            11.2         318.0
1 2023-05-26 01:00:00+02:00     NaN            10.4         308.0
2 2023-05-26 02:00:00+02:00  13.042             9.8         308.0
3 2023-05-26 03:00:00+02:00  13.116             9.5         304.0
4 2023-05-26 04:00:00+02:00  13.728             9.3         302.0

   Vindhastighet  Relativ luftfuktighet  Nederbördsmängd
0            4.5                   74.0              0.0
1            4.1                   76.0              0.0
2            4.1                   78.0              0.0
3            4.6                   81.0              0.0
4            4.0                   83.0              0.0
tid                      datetime64[us, Europe/Stockholm]
pm25                                              float64
Lufttemperatur                                    float64
Vindriktning                                      float64
Vindhastighet                                     float64
Relativ luftfuktighet                             float64
Nederbördsmängd                                   float64
dtype: object
tid                         0
pm25                      154
Lufttemperatur            536
Vindriktning              572
Vindhastighet             572
Relativ luftfuktighet     570
Nederbördsmängd          1069
dtype: int64

## Dataset för Modeller

In [38]:
df["target"] = df["pm25"].shift(-6)

In [40]:
df[["tid", "pm25", "target"]].head(10)

                        tid    pm25  target
0 2023-05-26 00:00:00+02:00     NaN  13.905
1 2023-05-26 01:00:00+02:00     NaN  13.739
2 2023-05-26 02:00:00+02:00  13.042  14.138
3 2023-05-26 03:00:00+02:00  13.116  12.972
4 2023-05-26 04:00:00+02:00  13.728  10.587
5 2023-05-26 05:00:00+02:00  13.913  10.422
6 2023-05-26 06:00:00+02:00  13.905   8.623
7 2023-05-26 07:00:00+02:00  13.739   7.389
8 2023-05-26 08:00:00+02:00  14.138   6.583
9 2023-05-26 09:00:00+02:00  12.972   6.217

# Features och Nan- bortagning

In [41]:
features = [
    "pm25",
    "Lufttemperatur",
    "Vindriktning",
    "Vindhastighet",
    "Relativ luftfuktighet",
    "Nederbördsmängd",
]

model_df = df.dropna(subset=features + ["target"]).copy()

print("Ursprungliga rader:", len(df))
print("Rader efter filtrering:", len(model_df))
print("Borttagna rader:", len(df) - len(model_df))

Ursprungliga rader: 22825
Rader efter filtrering: 21555
Borttagna rader: 1270

## Modell: Baseline

In [42]:
results = []   # Resultat sparas här

In [43]:
# Baseline

y_true = model_df["target"]
y_pred = model_df["pm25"]

baseline_results = evaluate_model(
    "Baseline",
    y_true,
    y_pred
)

results.append(baseline_results)

=== Baseline ===
MAE:  2.621
RMSE: 4.177
R²:   0.565

## Modell 1: Linerar Regression

In [44]:
X = model_df[features]
y = model_df["target"]

lr = LinearRegression()

lr.fit(X, y)

pred_lr = lr.predict(X)

lr_results = evaluate_model(
    "Linear Regression",
    y,
    pred_lr
)

results.append(lr_results)

=== Linear Regression ===
MAE:  2.527
RMSE: 3.941
R²:   0.613

## Model 2: Random Forrest

Börjar litet så det går snabbt att köra

In [45]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X, y)

pred_rf = rf.predict(X)

rf_results = evaluate_model(
    "Random Forest",
    y,
    pred_rf
)

results.append(rf_results)

=== Random Forest ===
MAE:  0.852
RMSE: 1.333
R²:   0.956

## Modell 3: HistGradientBoosting

In [46]:
hgb = HistGradientBoostingRegressor(
    random_state=42
)

hgb.fit(X, y)

pred_hgb = hgb.predict(X)

hgb_results = evaluate_model(
    "HistGradientBoosting",
    y,
    pred_hgb
)

results.append(hgb_results)

=== HistGradientBoosting ===
MAE:  2.139
RMSE: 3.182
R²:   0.748

## Jämförelse

In [47]:
results_df = pd.DataFrame(results)

results_df.sort_values(
    "RMSE",
    ascending=True
)

                  Model       MAE      RMSE        R2
2         Random Forest  0.851883  1.332621  0.955718
3  HistGradientBoosting  2.139380  3.181847  0.747550
1     Linear Regression  2.526700  3.940843  0.612746
0              Baseline  2.620982  4.176965  0.564950